#!/usr/bin/awk -f

# Creates sensible group separators in a CHARMM topology file.
# Typically used on str files generated by the CGenFF program.
# WARNING: atom order will change, invalidating all psf and possibly
# also coordinate files. Known issue: group assignment will be
# somewhat arbitrary on strongly unsaturated molecules.

# Copyright (C) 2012 Kenno Vanommeslaeghe
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

{ line=$0;$0=toupper(line);  # triggers parsing
  if ($1=="ATOM") {att=$2;idx[att]=++na;nam[na]=att;
    com[na]=substr(line,index(substr($0,5),att)+length(att)+5);next};
  if ($1=="BOND" || $1~"^DOUB") {buf[++nb]=line;arg=1;while ($++arg ~ "^[^!]") {
      at1=idx[$arg];at2=idx[$++arg];
      c1=++con[at1];c2=++con[at2];
      bat[at1,c1]=at2;bat[at2,c2]=at1 };
    next};
  if ($1=="GROUP") {next};
  if (na) {
    if ($1 == "" || $1 ~ "^!") {buf[++nb]=line;next};
    nun=na;
    for(i=1;i<=na;i++) if (con[i]==1) {par=bat[i,1];f=1;attach()};
    if (nun && f) for(i=1;i<=na;i++) if (! (i in grp)) {k=con[i];
          for(j=1;j<=k;j++) {par=bat[i,j];
            if (par in grp) if (grp[par]!="") {attach();break} };
          if (!nun) break};
    if (nun) for(par=1;par<=na;par++) if (! (par in grp)) {grp[par]=0;
          k=con[par];for(j=1;j<=k;j++){i=bat[par,j];if (!(i in grp)) attach()};
          if (! --nun) break};
    nun=na;while(nun){print "GROUP";for(i=1;i<=na;i++) if (grp[i]!="") break;
      print "ATOM",nam[i] com[i]; k=grp[i];
      for(j=1;j<=k;j++) {c=ch[i,j];print "ATOM",nam[c] com[c]};
      grp[i]="";nun-=k+1}
    for(i=1;i<=nb;i++) print buf[i];
    delete idx;delete nam;delete com;
    delete buf;delete con;delete bat;
    delete grp;delete ch;na="";nb=""};
  print line}
function attach() {if (! (par in grp)) nun--;
  c=++grp[par];ch[par,c]=i;grp[i]="";nun--}
